### ISSUE TITLE
模板图

### ISSUE THREAD

**Issue by smile-care** [majiawe/Tianchi-2021guangdong-industry-Algorithmic-competition--Defect-detection-of-ceramic-tile-Rank1#1]
你好，第一步传统特征使用的模板图是什么？

**Comment by majiawe** [comment]
比赛数据，赛题方提供！


 
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年3月31日 16:16:24
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [majiawe/Tianchi-2021guangdong-industry-Algorithmic-competition--Defect-detection-of-ceramic-tile-Rank1] 模板图 (#1)




 
你好，第一步传统特征使用的模板图是什么？

**Comment by smile-care** [comment]
> 比赛数据，赛题方提供！
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2021年3月31日 16:16:24 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [majiawe/Tianchi-2021guangdong-industry-Algorithmic-competition--Defect-detection-of-ceramic-tile-Rank1] 模板图 (#1) 你好，第一步传统特征使用的模板图是什么？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
